### ISSUE TITLE
an error occurs when make pycaffe

### ISSUE THREAD

**Issue by Engineering-Course** [fyu/dilation#10]
the python code should import caffe
but when I make pycaffe, an error occurs:

rsync -a --include '*/' --include '*.py' --exclude '*' \
          python/caffe/ build_master_release/python/caffe

What' s the problem?
I cloned the caffe from your link  [fyu/caffe-dilation](https://github.com/fyu/caffe-dilation)

**Comment by fyu** [comment]
That's is not an error message. It says that the files under `python/caffe/` is copied to `${BUILD_DIR}_${GIT_BRANCH}_release/python/caffe` folder. So instead of adding `python/caffe/` to `PYTHONPATH`, you can add `${BUILD_DIR}_${GIT_BRANCH}_release/python/caffe`. The benefits of doing this is discussed in readme: https://github.com/fyu/caffe-dilation#build.

**Comment by Engineering-Course** [comment]
Solved. Thanks a lot~
